In [1]:
import numpy as np

In [2]:
a = np.array([1, -2, 4, -5, 3, -1, 3, 4, 1]).reshape(3,3)
np.linalg.det(a)

-113.00000000000003

In [3]:
28*28*100+ 100*100+100*10


89400

In [6]:
-np.log(1/10)

2.3025850929940455

In [7]:
def readData():
    data = ['<s> hoc sinh hoc sinh hoc </s> <s> sinh hoc la mot mon khoa hoc </s> <s> hoc sinh hoc khoa hoc </s>']
    dat=[]
    for i in range(len(data)):
        for word in data[i].split():
            dat.append(word)
    print(dat)
    return dat

def createBigram(data):
   listOfBigrams = []
   bigramCounts = {}
   unigramCounts = {}
   for i in range(len(data)-1):
      if i < len(data) - 1 and data[i+1].islower():

         listOfBigrams.append((data[i], data[i + 1]))

         if (data[i], data[i+1]) in bigramCounts:
            bigramCounts[(data[i], data[i + 1])] += 1
         else:
            bigramCounts[(data[i], data[i + 1])] = 1

      if data[i] in unigramCounts:
         unigramCounts[data[i]] += 1
      else:
         unigramCounts[data[i]] = 1
   return listOfBigrams, unigramCounts, bigramCounts


def calcBigramProb(listOfBigrams, unigramCounts, bigramCounts):
    listOfProb = {}
    for bigram in listOfBigrams:
        word1 = bigram[0]
        word2 = bigram[1]
        listOfProb[bigram] = (bigramCounts.get(bigram))/(unigramCounts.get(word1))
    return listOfProb


In [11]:
data = readData()
listOfBigrams, unigramCounts, bigramCounts = createBigram(data)

print("\n All the possible Bigrams are ")
print(listOfBigrams)

print("\n Bigrams along with their frequency ")
print(bigramCounts)

print("\n Unigrams along with their frequency ")
print(unigramCounts)

bigramProb = calcBigramProb(listOfBigrams, unigramCounts, bigramCounts)

print("\n Bigrams along with their probability ")
print(bigramProb)
inputList="hoc"
splt=inputList.split()
outputProb1 = 1
bilist=[]
bigrm=[]

for i in range(len(splt) - 1):
    if i < len(splt) - 1:

        bilist.append((splt[i], splt[i + 1]))

print("\n The bigrams in given sentence are ")
print(bilist)
for i in range(len(bilist)):
    if bilist[i] in bigramProb:

        outputProb1 *= bigramProb[bilist[i]]
    else:

        outputProb1 *= 0
print('\n' + 'Probablility of sentence \"', inputList , '\" = ' + str(outputProb1))



['<s>', 'hoc', 'sinh', 'hoc', 'sinh', 'hoc', '</s>', '<s>', 'sinh', 'hoc', 'la', 'mot', 'mon', 'khoa', 'hoc', '</s>', '<s>', 'hoc', 'sinh', 'hoc', 'khoa', 'hoc', '</s>']

 All the possible Bigrams are 
[('<s>', 'hoc'), ('hoc', 'sinh'), ('sinh', 'hoc'), ('hoc', 'sinh'), ('sinh', 'hoc'), ('hoc', '</s>'), ('</s>', '<s>'), ('<s>', 'sinh'), ('sinh', 'hoc'), ('hoc', 'la'), ('la', 'mot'), ('mot', 'mon'), ('mon', 'khoa'), ('khoa', 'hoc'), ('hoc', '</s>'), ('</s>', '<s>'), ('<s>', 'hoc'), ('hoc', 'sinh'), ('sinh', 'hoc'), ('hoc', 'khoa'), ('khoa', 'hoc'), ('hoc', '</s>')]

 Bigrams along with their frequency 
{('<s>', 'hoc'): 2, ('hoc', 'sinh'): 3, ('sinh', 'hoc'): 4, ('hoc', '</s>'): 3, ('</s>', '<s>'): 2, ('<s>', 'sinh'): 1, ('hoc', 'la'): 1, ('la', 'mot'): 1, ('mot', 'mon'): 1, ('mon', 'khoa'): 1, ('khoa', 'hoc'): 2, ('hoc', 'khoa'): 1}

 Unigrams along with their frequency 
{'<s>': 3, 'hoc': 8, 'sinh': 4, '</s>': 2, 'la': 1, 'mot': 1, 'mon': 1, 'khoa': 2}

 Bigrams along with their probabil

In [18]:
import pandas as pd
pd.Series(listOfBigrams).value_counts().sum()

22

In [19]:
4/22

0.18181818181818182

In [21]:
12000*64*1000

768000000

In [23]:
'furuike ya'.count(i)

1

In [27]:
def dem_nguyen_am(string):
    return sum([string.count(i) for i in ['a', 'e', 'u', 'i', 'o']])
dem_nguyen_am('furuike ya')    

5

In [29]:
[1,2,3] is [1,2,3]

False

In [84]:
s = '1024 512 64 512 512'

In [85]:
numbers = np.array(list(map(int, s.split())))

In [87]:
u_num = 512
indices = np.where(numbers == u_num)[0] 
if len(indices) >= 2:
    numbers[indices[:2]] = 2*u_num
    print(numbers[indices[1]])
    np.delete(numbers, np.where(numbers == 2*u_num))
numbers

array([1024, 1024,   64, 1024,  512])

In [62]:
for u_num in np.unique(numbers):
    indices = np.where(numbers == u_num)[0] 
    if len(indices) >= 2:
        numbers[indices[:2]] = 2*u_num
    print(numbers)


[1024  512  128  512  512]
[1024 1024  128 1024  512]
[2048 2048  128 1024  512]


In [58]:
numbers

array([2048,  256,  256,  128, 2048])